### ISSUE TITLE
Crash with Mekanism Logistical Sorter

### ISSUE THREAD

**Issue by LocalBoomer** [Shadows-of-Fire/FastSuite#2]
https://controlc.com/6bf7ff78

I added Fast Suite to my custom modpack and one of my Logistical Transporters now crashes the server after a few seconds of loading in. The same one crashes each time (I've made six or so attempts to load in at this point.) and I have others in the world so I don't know why that one is causing issues.

MC 1.16.5
Forge 36.1.13
Fast Suite 1.0.0
all official Mekanism modules 10.0.21.448

**Comment by Shadows-of-Fire** [comment]
This is an out of memory error, you'll need to dedicate more RAM to the game.

**Comment by LocalBoomer** [comment]
I don't mean to seem rude but I too can read text files. 

The issue is resolved by removing fast suite and the instance already has 10 gig of ram allocated and rarely needs more than 8. I'm not sure why adding fast suite is increasing the ram requirements by another 2 gig all on it's own. Is this normal behaviour for it?

**Comment by Shadows-of-Fire** [comment]
It *might* be related to #1 so we can see if the next update resolves it.

Since it looks like the actual memory error is coming out of arraylist allocation.  FS on it's own does need a bit of memory (Since the recipe list requires 1 node per recipe, and each node holds 3 pointers), but it shouldn't be in the gigabyte space unless there are actually a couple hundred thousand recipes...
